### ISSUE TITLE
expose API for listing all currently detected mesos masters, not just the leader

### ISSUE THREAD

**Issue by jdef** [mesos/mesos-go#110]
/cc @kozyraki

**Comment by tnachen** [comment]
Just curious, what's the reason for exposing all masters?

**Comment by jdef** [comment]
christos mentioned that the HDFS framework wanted IP addresses, registered in mesos-dns, for all mesos masters. The detection API already listened for changes to the mesos-master list, it just didn't provide a hook for those interested.

**Comment by jdef** [comment]
to further clarify, there are two parts to the problem this is attempting to solve:

1. there exist frameworks that want to dynamically obtain the list of all ZK nodes in the cluster, under the **assumption** that **every mesos master node also runs ZK**. older versions of zookeeper don't allow dynamic discovery, so this is really a workaround for that based on an assumption.
1. mesos-dns, which uses this zookeeper detection helper, could provide DNS entries for all mesos master nodes if it could detect them through the APIs presented here. clients of mesos-dns could then query the server for a list of all mesos masters. they could then assume that all of those masters are running ZK.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/mesos-dns/issues/166

**Comment by lloesche** [comment]
@tnachen the nginx in DCOS proxies to master.mesos. When designing it like that the assumption was that master.mesos would contain all the masters. We only later found out that that's only the case for when the masters are hard coded in the mesos-dns config. When running via zookeeper it only returns the current leader at which point it's essentially the same as leader.mesos.
This currently breaks HA for the DCOS UI. E.g. if marathon on the current leader becomes unresponsive then nginx will still proxy requests to it because it doesn't know about the other master nodes.
So having master.mesos always return the masters would be extremely helpful to us. I'd also argue that from a user point of view it's what I would expect to happen when I query that record.
