### ISSUE TITLE
executor no launched from Docker container

### ISSUE THREAD

**Issue by milosgajdos83** [mesos/mesos-go#126]
I've tried to play with `mesos-go` API to create a simple framework. I'm trying to launch an executor as a docker container from a given image.

The framework is created fine, however when I try to launch a task from scheduler it gets never launched and hangs on:

`2015/05/22 16:58:18 Launching  1 tasks for offer 20150522-165706-1476399532-5050-1-O0`

I had a look into logs and found the following error:

`[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mesos.internal.LaunchTasksMessage" because it is missing required fields: tasks[0].executor.command
`

I don't understand why should I specify a command info when my executor should be started from docker  container ? The code I'm testing this on is in a following [gist](https://gist.github.com/milosgajdos83/f76cf47233cdd073eb92)

**Comment by tsenart** [comment]
Hi Milos,

Would you be able to provide more details on your specific environment

* What revision of the library are you using?
* What mesos version?
* What OS and architecture?
* Anything else you may find relevant...?

Thanks,
Tomás

**Comment by milosgajdos83** [comment]
Hi, sorry for late update - my GH client simply decided to go on a holiday break before summer even started :-)

The answers to your questions:
- I was using the latest ie `HEAD` of `github.com/mesos/mesos-go` package
- You can see the mesos version in `docker-compose` file in the [repo](https://github.com/milosgajdos83/taurus/blob/master/docker-compose.yml) (I have removed all the dysfunctional bits from the repo - the stuff which is there is a total PoC and only schedules hard coded `nginx` container - it's not using executor at all - but it can give you an idea of my work env when I stumbled on this issue)
- I tested this on `Ubuntu Trusty` ie `14.04` release host:
`Linux docker-hacks 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

I guess the main question really for me is whether what I'm trying to do is even feasible or rather if I'm completely missing the point or misunderstanding this.

Like I said the idea was to start the executor in a separate Docker container on framework startup. Or in other words: get the executor started by framework when the frameworks starts. This could be entirely wrong thinking, though.

**Comment by tsenart** [comment]
I see that you're running Mesos 0.22.1. @jdef: Correct me if I'm wrong but I think we still need to update our Protobufs for that version https://github.com/mesos/mesos-go/issues/121.

I suspect this is why you're running into this problem.

**Comment by jdef** [comment]
The protobufs are behind, but I don't suspect that as the root cause in
this case. From the docs in mesos.proto:

"""
  required CommandInfo command = 7;

  // Executor provided with a container will launch the container
  // with the executor's CommandInfo and we expect the container to
  // act as a Mesos executor.
  optional ContainerInfo container = 11;
"""

You still need to provide a CommandInfo for ExecutorInfo, even if you're
running the executor in a docker container. I don't see any required
elements in CommandInfo, so you should be able to set a mostly empty one,
&mesosproto.CommandInfo{Shell: false} (assuming that your docker image has
a configured entrypoint or cmd).

For reference, Marathon always creates a CommandInfo. If no command is
specified, it sets Shell to false:
https://github.com/mesosphere/marathon/blob/cdcc3c90c7268ecb482e9611ffd4831ffcd442b2/src/main/scala/mesosphere/mesos/TaskBuilder.scala#L194

**Comment by milosgajdos83** [comment]
Let me verify this at some point today.

It does seem that specifying empty `CommandInfo` could solve this. I'll test this and update the issue.

**Comment by jdef** [comment]
Any update here?

**Comment by milosgajdos83** [comment]
Hi @jdef sorry for late reply! I was totally swamped this week.

I can confirm - providing empty `CommandInfo` does seem to resolve this.

Thanks!

**Comment by jdef** [comment]
thanks for confirming
