### ISSUE TITLE
Stability of Mesos-go

### ISSUE THREAD

**Issue by dhilipkumars** [mesos/mesos-go#217]
Hi Team,

We are planning to start a project using mesos-go which will eventually be used in production environment.  The below disclaimer seems to say that the status is currently alpha.

```
This project is undergoing a complete rewrite happening in the next branch. These bindings will integrate exclusively with the new public Mesos HTTP API.

The current version of the bindings are considered alpha and won't see any major development besides critical compatibility and bug fixes.
```

what would you recommend? should we start using the 'next' branch or should start using the 'master' branch.   

When do you actually plan to make it stable? 

Thanks in Advance

**Comment by jdef** [comment]
The next branch isn't ready for consumption, and may not be for some time.
The master branch has mostly settled and won't see many feature changes
going forward. Reported bugs will be prioritized and patched accordingly.
PR's that add new functionality are not guaranteed to be merged since new
development is focused on the next branch. Please develop against the
master branch.

New Mesos API's are being introduced via the HTTP v1 API mechanism and so
they won't be available to mesos-go users until an alpha version of the
next branch is ready. It's likely that we'll implement a callback adapter
that allows users of the old API to more easily integrate with the "next"
branch.

HTH

**Comment by dhilipkumars** [comment]
Awesome news.  Thanks for the response. Closing the issue.
