### ISSUE TITLE
Question: Framework development in Golang

### ISSUE THREAD

**Issue by krish7919** [mesos/mesos-go#254]
I am new to developing framework and I have a custom use-case in mind.
I am confused as to why we cannot develop frameworks for mesos in golang  by default.
My understanding of the process is that all the communication happens over various protobuf messages and hence, any language that supports protobuf should be good enough.
Am I missing something?
Thanks.

**Comment by jdef** [comment]
Sure, any lang that supports protobuf is just fine. If you're writing a
framework in Go there's no requirement that you use mesos-go. Before the
HTTP v1 API there were many undocumented requirements regarding the
protocol for interacting with mesos masters and agents (even though it was
protobuf, it wasn't really valid HTTP). The new v1 API is much easier to
consume and is actually HTTP compatible. You're free to write your own
integration code to interact with the v1 API. At this point in time the
work in the mesos-go/next branch is a thin convenience layer for
interacting with the API. It's much more lightweight than mesos-go/master.
It's also designed so that you can pick and choose which parts to use. If
you only want to use the generated protobuf code that's pretty easy to do.
If you want that + the events API you can do that too (without also
importing the additional business logic of the HTTP layer or the reference
scheduler controller).

The mesos-go/next branch is currently under development. If you've tried it
and have some feedback to share we'd love to hear it.

**Comment by krish7919** [comment]
Can we use golang framework with the 0.25 version of mesos?
Coz that's what we currently use.

**Comment by jdef** [comment]
it **should** work since mesos-go/master was last sync'd to mesos-0.26 protos. generally things work OK as long as the proto versions match, or are 1 release off.

**Comment by thehydroimpulse** [comment]
@jdef Is the next branch currently usable?

**Comment by ajwerner** [comment]
@jdef Bump on the usability of the next branch. It's getting to the point where the feature gap is relatively large. What issues need to be resolved to feel more comfortable using it?

**Comment by jdef** [comment]
#274
