### ISSUE TITLE
Slave implementation

### ISSUE THREAD

**Issue by alexandrem** [mesos/mesos-go#91]
Hi,
I'm wondering if it'd be possible to also implement the Slave interface in mesos-go, so we could build a pure slave in Go without any dependency on libmesos.

Would that work?

**Comment by jdef** [comment]
It's probably do-able. It would be a ton of work, and the pure bindings,
which are a higher priority, still need a good amount of TLC.

If it's something that interests you and you're willing to invest the time
in a working prototype - then we'd probably accept a PR :) Otherwise I
don't see it happening very soon.

What are you really trying to accomplish? Building/running Mesos on a
currently non-supported OS?

On Fri, Feb 20, 2015 at 1:21 PM, Alexandre Mclean <notifications@github.com>
wrote:

> Hi,
> I'm wondering if it'd be possible to also implement the Slave interface in
> mesos-go, so we could build a pure slave in Go without any dependency on
> libmesos.
>
> Would that work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesos/mesos-go/issues/91>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by alexandrem** [comment]
Hi jdef,
yes the goal would be to have a portable Slave/executor to Windows platforms.

Not sure what would be the easiest/best approach to accomplish that and if it's a reasonable thing to do :)

**Comment by jdef** [comment]
closing this out - it's really not the job of the bindings to take care of this. as discussed on the mailing list, you probably want a custom containerizer.
